Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  M = PUT NUMBER OF REQUIRED VMs
  (1..M).each do |i|
  config.vm.define "master#{i}" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "ubuntu-#{i}"
    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "ubuntu-#{i}"]
    end
    master.vm.provision "shell", inline: <<-SHELL
    sudo su && echo "ADD YOUR SSH PUBLIC KEY" >> /root/.ssh/authorized_keys
    SHELL
    end
  end
end
