Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox" do |vb|
   vb.memory = "4096"
  end  
  config.vm.provision "shell", inline: <<-SHELL
  sudo su && echo "ADD YOUR SSH PUBLIC KEY" >> /root/.ssh/authorized_keys
  SHELL
end
