Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  M = PUT NUMBER OF MASTER NODES
  (1..M).each do |i|
  config.vm.define "master#{i}" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "k8s-master-#{i}"
    master.vm.network "public_network", bridge: 'wlo1', ip: "ADD YOUR IP RANGE#{i}"
    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "k8s-master-#{i}"]
    end
    master.vm.provision "shell", inline: <<-SHELL
    sudo su && echo "ADD YOUR SSH PUBLIC KEY" >> /root/.ssh/authorized_keys
    SHELL
    end
  end
  
  N = PUT NUMBER OF WORKER NODES
  (1..N).each do |i|
  config.vm.define "node#{i}" do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = "k8s-worker-0#{i}"
    node.vm.network "public_network", bridge: 'wlo1', ip: "ADD YOUR IP RANGE#{i}"
    node.vm.provider :virtualbox do |v|      
      v.customize ["modifyvm", :id, "--memory", 3072]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "k8s-worker-0#{i}"]
    end
    node.vm.provision "shell", inline: <<-SHELL
    sudo su && echo "ADD YOUR SSH PUBLIC KEY" >> /root/.ssh/authorized_keys
    SHELL
    end
  end
end
